import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Free Photo Editor - Change Background, Adjust Brightness & Contrast Online | UnderlayX",
  description:
    "Free online photo editor to change background, adjust brightness, contrast, saturation. Edit photos with AI - remove background, enhance colors, and apply filters. Professional photo editing made simple.",
  keywords: [
    "change background",
    "background changer",
    "change photo background",
    "remove background",
    "background removal",
    "adjust brightness",
    "photo brightness",
    "brightness adjustment",
    "adjust contrast",
    "photo contrast",
    "contrast adjustment",
    "adjust saturation",
    "photo saturation",
    "saturation adjustment",
    "photo editor",
    "edit photos online",
    "free photo editor",
    "online photo editor",
    "photo editing online",
    "AI photo editing",
    "photo enhancement",
    "image editing tools",
    "photo filters",
    "image adjustment",
    "photo retouching",
    "background editor",
    "photo background editor",
    "change image background",
    "background replacement",
    "photo background changer",
    "edit background",
    "background editing",
    "photo color adjustment",
    "image brightness",
    "image contrast",
    "image saturation",
    "photo color correction",
    "image color adjustment",
    "photo filters online",
    "free image editor",
    "online image editing",
    "photo editor free",
    "image editing free",
    "photo enhancement online",
    "background removal tool",
    "photo background tool",
    "image background editor",
    "photo editing website",
    "online photo retouching",
    "photo color enhancement",
    "image color correction",
    "photo adjustment tool",
    "image adjustment tool",
    "photo editing platform",
    "online photo editing tool",
    "free photo editing software",
    "photo editing online free",
    "image editing online free",
    "photo background removal",
    "change background online",
    "background changer online",
    "photo background replacement",
    "image background changer",
    "photo background editor online",
    "free background editor",
    "online background editor",
    "photo background tool online",
    "image background tool",
    "photo background removal tool",
    "change photo background online",
    "edit photo background",
    "photo background editing",
    "image background editing",
    "photo background modification",
    "image background modification",
    "photo background adjustment",
    "image background adjustment",
    "photo background enhancement",
    "image background enhancement",
    "photo background correction",
    "image background correction",
    "photo background optimization",
    "image background optimization",
    "photo background improvement",
    "image background improvement",
    "photo background customization",
    "image background customization",
    "photo background personalization",
    "image background personalization",
    "photo background transformation",
    "image background transformation",
    "photo background manipulation",
    "image background manipulation",
    "photo background processing",
    "image background processing",
    "photo background refinement",
    "image background refinement",
    "photo background tuning",
    "image background tuning",
    "photo background fine-tuning",
    "image background fine-tuning",
  ],
  openGraph: {
    title:
      "Free Photo Editor - Change Background, Adjust Brightness & Contrast Online | UnderlayX",
    description:
      "Free online photo editor to change background, adjust brightness, contrast, saturation. Edit photos with AI - remove background, enhance colors, and apply filters. Professional photo editing made simple.",
    url: "https://underlayx.com/photo-editor",
    siteName: "UnderlayX",
    images: [
      {
        url: "https://underlayx.com/og-image.png",
        width: 1200,
        height: 630,
        alt: "UnderlayX Photo Editor - Edit Photos Online",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title:
      "Free Photo Editor - Change Background, Adjust Brightness & Contrast Online | UnderlayX",
    description:
      "Free online photo editor to change background, adjust brightness, contrast, saturation. Edit photos with AI - remove background, enhance colors, and apply filters.",
    images: ["https://underlayx.com/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://underlayx.com/photo-editor",
  },
};

export default function PhotoEditorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
